Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TaskManager.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

              
    }
}

Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManager.Helpers;
using TaskManager.Infrastructure;
using TaskManager.Models;
using TaskManager.Repository;

namespace TaskManager.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
       
        /// <summary>
        /// Load the status, categories and profile drop downs
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            EntitiesDb db = new EntitiesDb();

            
            UserInfoHelper ui = new UserInfoHelper();
            Tasks tasks = new Tasks();
            tasks.Priorities = db.ref_Priorities;
            tasks.Status = db.ref_Status;
            tasks.Categories = db.Categories;
            tasks.Profiles = db.UserProfileMs;
            return View(tasks);
        }

        public ActionResult Create()
        {
            return View();
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            
        </div>
    </section>
}
<h3>Home Page</h3>
Go to @Html.ActionLink("Task Manager", "Index", "Tasks") 